"""
Recommendation System Dashboard
-------------------------------------------------------------

This page explores the product recommendations generated by three
engines built for this project:

    - Popularity Ranking            -> popularity_df
    - Customer Collaborative Filter -> customer_df
    - Item-Item Similarity          -> item_df

All three come directly from the project's own recommendation
outputs (popularity_recommendations.csv,
customer_collaborative_recommendations.csv,
item_collaborative_recommendations.csv). No external data,
images, or text is used anywhere on this page.

Author: Arin Bhardwaj
Project: Intelligent Customer Analytics Platform
"""

import pandas as pd
import plotly.express as px
import streamlit as st

from utils.cache import load_csv
from utils.config import RECOMMENDATION_DATA_DIR

# ==========================================================
# LOAD DATA
# ==========================================================

popularity_df = load_csv(
    RECOMMENDATION_DATA_DIR / "popularity_recommendations.csv"
)

customer_df = load_csv(
    RECOMMENDATION_DATA_DIR / "customer_collaborative_recommendations.csv"
)

item_df = load_csv(
    RECOMMENDATION_DATA_DIR / "item_collaborative_recommendations.csv"
)


def sorted_unique(series):
    """
    Return sorted unique values from a column, safely, even if
    the column contains a missing value (NaN would otherwise
    break sorted() when mixed with strings).
    """

    return sorted(series.dropna().unique().tolist())

# ==========================================================
# PAGE HEADER
# ==========================================================

st.title("🎯 Recommendation System")

st.markdown(
    """
This page explores product recommendations built from three engines:

- **Popularity Ranking** — what sells the most, for everyone
- **Customer Collaborative Filtering** — recommendations tailored to a specific customer
- **Item-Item Similarity** — products frequently bought alongside each other

Use the explorers below to see recommendations for any customer or product.
"""
)

st.divider()

# ==========================================================
# KPI OVERVIEW
# ==========================================================

st.header("📌 Recommendations at a Glance")

total_products = popularity_df["StockCode"].nunique()

total_customers_covered = customer_df["CustomerID"].nunique()

total_customer_recommendations = len(customer_df)

total_item_recommendations = len(item_df)

avg_popularity_score = popularity_df["PopularityScore"].mean()

avg_similarity_score = item_df["SimilarityScore"].mean()

total_purchase_volume = popularity_df["PurchaseCount"].sum()

total_recommended_revenue = popularity_df["TotalRevenue"].sum()

k1, k2, k3, k4 = st.columns(4)

with k1:

    st.metric(
        "Products",
        f"{total_products:,}",
    )

with k2:

    st.metric(
        "Customers Covered",
        f"{total_customers_covered:,}",
    )

with k3:

    st.metric(
        "Customer Recommendations",
        f"{total_customer_recommendations:,}",
    )

with k4:

    st.metric(
        "Item Recommendations",
        f"{total_item_recommendations:,}",
    )

k5, k6, k7, k8 = st.columns(4)

with k5:

    st.metric(
        "Avg Popularity Score",
        f"{avg_popularity_score:.2f}",
    )

with k6:

    st.metric(
        "Avg Similarity Score",
        f"{avg_similarity_score:.2f}",
    )

with k7:

    st.metric(
        "Total Purchase Volume",
        f"{int(total_purchase_volume):,}",
    )

with k8:

    st.metric(
        "Revenue Behind Top Products",
        f"£{total_recommended_revenue:,.0f}",
    )

st.divider()

# ==========================================================
# DATASET PREVIEW
# ==========================================================

st.header("👀 Recommendation Datasets")

dataset_choice = st.radio(
    "Choose a dataset to preview",
    ["Popularity", "Customer Collaborative", "Item Collaborative"],
    horizontal=True,
)

if dataset_choice == "Popularity":

    st.dataframe(
        popularity_df.head(10),
        use_container_width=True,
        hide_index=True,
    )

elif dataset_choice == "Customer Collaborative":

    st.dataframe(
        customer_df.head(10),
        use_container_width=True,
        hide_index=True,
    )

else:

    st.dataframe(
        item_df.head(10),
        use_container_width=True,
        hide_index=True,
    )

st.divider()

# ==========================================================
# MOST POPULAR PRODUCTS
# ==========================================================

st.header("🏆 Most Popular Products")

st.caption(
    "Products ranked by popularity score, based on purchase volume and revenue."
)

top_n = st.slider(
    "Number of products to show",
    min_value=5,
    max_value=30,
    value=10,
)

top_products = (
    popularity_df.sort_values("PopularityRank")
    .head(top_n)
)

fig_top_products = px.bar(
    top_products,
    x="PopularityScore",
    y="Description",
    orientation="h",
    color="PopularityScore",
    color_continuous_scale="Blues",
    template="plotly_dark",
)

fig_top_products.update_layout(
    height=450,
    yaxis=dict(autorange="reversed"),
    margin=dict(l=10, r=10, t=10, b=10),
    coloraxis_showscale=False,
)

st.plotly_chart(
    fig_top_products,
    use_container_width=True,
)

st.dataframe(
    top_products[
        [
            "PopularityRank",
            "StockCode",
            "Description",
            "PopularityScore",
            "PurchaseCount",
            "TotalRevenue",
        ]
    ],
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ==========================================================
# POPULARITY VS REVENUE
# ==========================================================

st.header("💰 Popularity vs Revenue")

st.caption(
    "Each dot is a product. Position shows purchase count and total "
    "revenue; larger dots have a higher popularity score."
)

fig_pop_revenue = px.scatter(
    popularity_df.head(100),
    x="PurchaseCount",
    y="TotalRevenue",
    size="PopularityScore",
    hover_data=["Description", "StockCode"],
    template="plotly_dark",
    render_mode="svg",
)

fig_pop_revenue.update_layout(
    height=420,
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_pop_revenue,
    use_container_width=True,
)

st.divider()

# ==========================================================
# REVENUE SHARE (TREEMAP)
# ==========================================================

st.header("🧩 Revenue Share of Top Products")

st.caption("Each block represents a product — larger blocks generated more revenue.")

treemap_data = (
    popularity_df.sort_values("TotalRevenue", ascending=False)
    .head(30)
)

fig_treemap = px.treemap(
    treemap_data,
    path=["Description"],
    values="TotalRevenue",
    template="plotly_dark",
)

fig_treemap.update_layout(
    height=450,
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_treemap,
    use_container_width=True,
)

st.divider()

# ==========================================================
# STRONGEST PRODUCT PAIRS OVERALL
# ==========================================================

st.header("🔗 Top 20 Strongest Product Pairings")

st.caption(
    "Across the entire item-item similarity dataset, these are the "
    "strongest product-to-product relationships found."
)

top_pairs = (
    item_df.sort_values("SimilarityScore", ascending=False)
    .head(20)
)

fig_top_pairs = px.bar(
    top_pairs,
    x="SimilarityScore",
    y="Description",
    orientation="h",
    color="SimilarityScore",
    color_continuous_scale="Purples",
    template="plotly_dark",
)

fig_top_pairs.update_layout(
    height=480,
    yaxis=dict(autorange="reversed"),
    margin=dict(l=10, r=10, t=10, b=10),
    coloraxis_showscale=False,
)

st.plotly_chart(
    fig_top_pairs,
    use_container_width=True,
)

st.dataframe(
    top_pairs[
        [
            "StockCode",
            "Description",
            "SimilarityScore",
        ]
    ],
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ==========================================================
# CUSTOMERS WITH THE MOST RECOMMENDATIONS
# ==========================================================

st.header("👥 Customers with the Most Recommendations")

st.caption(
    "Customers who were matched with the largest number of recommended products."
)

customer_rec_counts = (
    customer_df.groupby("CustomerID", as_index=False)
    .agg(
        RecommendedProducts=("StockCode", "count"),
        AvgNeighborCount=("NeighborCount", "mean"),
    )
    .round(2)
    .sort_values("RecommendedProducts", ascending=False)
    .head(15)
)

fig_customer_recs = px.bar(
    customer_rec_counts,
    x="RecommendedProducts",
    y=customer_rec_counts["CustomerID"].astype(str),
    orientation="h",
    template="plotly_dark",
)

fig_customer_recs.update_layout(
    height=420,
    yaxis=dict(
        autorange="reversed",
        title="Customer ID",
    ),
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_customer_recs,
    use_container_width=True,
)

st.dataframe(
    customer_rec_counts,
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ==========================================================
# CUSTOMER RECOMMENDATION EXPLORER
# ==========================================================

st.header("👤 Recommendations for a Customer")

st.caption(
    "Products recommended for a specific customer using collaborative filtering."
)

selected_customer = st.selectbox(
    "Select a Customer ID",
    sorted_unique(customer_df["CustomerID"]),
)

customer_result = customer_df[
    customer_df["CustomerID"] == selected_customer
]

cust1, cust2 = st.columns(2)

with cust1:

    st.metric(
        "Recommended Products",
        customer_result["StockCode"].nunique(),
    )

with cust2:

    st.metric(
        "Avg Neighbour Count",
        f"{customer_result['NeighborCount'].mean():.0f}",
    )

st.dataframe(
    customer_result[
        [
            "StockCode",
            "NeighborCount",
        ]
    ],
    use_container_width=True,
    hide_index=True,
)

st.caption("Recommended products enriched with their popularity ranking:")

customer_result_enriched = customer_result.merge(
    popularity_df[
        [
            "StockCode",
            "Description",
            "PopularityScore",
            "PopularityRank",
        ]
    ],
    on="StockCode",
    how="left",
).sort_values("PopularityRank")

st.dataframe(
    customer_result_enriched[
        [
            "StockCode",
            "Description",
            "NeighborCount",
            "PopularityScore",
            "PopularityRank",
        ]
    ],
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ==========================================================
# PRODUCT SIMILARITY EXPLORER
# ==========================================================

st.header("📦 Products Similar To...")

st.caption(
    "Products frequently associated with a selected product, based on item-item similarity."
)

selected_product = st.selectbox(
    "Select a Product (Stock Code)",
    sorted_unique(item_df["StockCode"]),
)

product_result = item_df[
    item_df["StockCode"] == selected_product
].sort_values("SimilarityScore", ascending=False)

prod1, prod2 = st.columns(2)

with prod1:

    st.metric(
        "Similar Products Found",
        len(product_result),
    )

with prod2:

    st.metric(
        "Average Similarity",
        f"{product_result['SimilarityScore'].mean():.3f}",
    )

fig_similar_products = px.bar(
    product_result.head(10),
    x="SimilarityScore",
    y="Description",
    orientation="h",
    template="plotly_dark",
)

fig_similar_products.update_layout(
    height=380,
    yaxis=dict(autorange="reversed"),
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_similar_products,
    use_container_width=True,
)

st.dataframe(
    product_result[
        [
            "Description",
            "SimilarityScore",
        ]
    ],
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ==========================================================
# HYBRID RECOMMENDATION PREVIEW
# ==========================================================

st.header("🧠 Hybrid Recommendation Preview")

st.caption(
    "Combines popularity and item similarity: for the product selected above, "
    "this ranks its similar products by blending similarity with how popular "
    "each recommended product already is."
)

hybrid_source_df = item_df[
    item_df["StockCode"] == selected_product
].sort_values("SimilarityScore", ascending=False)

hybrid_df = hybrid_source_df.merge(
    popularity_df[["StockCode", "PopularityScore"]],
    on="StockCode",
    how="left",
)

hybrid_df["PopularityScore"] = hybrid_df["PopularityScore"].fillna(0)

hybrid_df["HybridScore"] = (
    0.6 * hybrid_df["SimilarityScore"]
    + 0.4 * (hybrid_df["PopularityScore"] / hybrid_df["PopularityScore"].max())
).round(3)

hybrid_df = hybrid_df.sort_values("HybridScore", ascending=False)

fig_hybrid = px.bar(
    hybrid_df.head(10),
    x="HybridScore",
    y="Description",
    orientation="h",
    template="plotly_dark",
)

fig_hybrid.update_layout(
    height=380,
    yaxis=dict(autorange="reversed"),
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_hybrid,
    use_container_width=True,
)

st.dataframe(
    hybrid_df[
        [
            "Description",
            "SimilarityScore",
            "PopularityScore",
            "HybridScore",
        ]
    ].head(10),
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ==========================================================
# ENGINE COMPARISON
# ==========================================================

st.header("⚖️ Recommendation Engine Comparison")

st.caption(
    "A side-by-side look at the scale of each recommendation engine."
)

engine_comparison = pd.DataFrame(
    {
        "Engine": [
            "Popularity Ranking",
            "Customer Collaborative Filtering",
            "Item-Item Similarity",
        ],
        "Records": [
            len(popularity_df),
            len(customer_df),
            len(item_df),
        ],
        "Unique Products Covered": [
            popularity_df["StockCode"].nunique(),
            customer_df["StockCode"].nunique(),
            item_df["StockCode"].nunique(),
        ],
    }
)

engine_left, engine_right = st.columns([1.2, 1])

with engine_left:

    fig_engine_comparison = px.bar(
        engine_comparison,
        x="Engine",
        y="Records",
        color="Engine",
        template="plotly_dark",
    )

    fig_engine_comparison.update_layout(
        height=360,
        showlegend=False,
        margin=dict(l=10, r=10, t=10, b=10),
    )

    st.plotly_chart(
        fig_engine_comparison,
        use_container_width=True,
    )

with engine_right:

    st.dataframe(
        engine_comparison,
        use_container_width=True,
        hide_index=True,
    )

st.divider()

# ==========================================================
# CUSTOMER ENGAGEMENT — NEIGHBOUR COUNT DISTRIBUTION
# ==========================================================

st.header("📊 Customer Collaborative Filtering Coverage")

st.caption(
    "How many neighbouring customers were used to generate recommendations, "
    "across all customers."
)

fig_neighbor_hist = px.histogram(
    customer_df,
    x="NeighborCount",
    nbins=30,
    template="plotly_dark",
)

fig_neighbor_hist.update_layout(
    height=360,
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_neighbor_hist,
    use_container_width=True,
)

st.divider()

# ==========================================================
# SIMILARITY SCORE DISTRIBUTION
# ==========================================================

st.header("📊 Item Similarity Score Distribution")

st.caption(
    "How strong the item-to-item similarity scores are across all product pairs."
)

fig_similarity_hist = px.histogram(
    item_df,
    x="SimilarityScore",
    nbins=30,
    template="plotly_dark",
)

fig_similarity_hist.update_layout(
    height=360,
    margin=dict(l=10, r=10, t=10, b=10),
)

st.plotly_chart(
    fig_similarity_hist,
    use_container_width=True,
)

st.divider()

# ==========================================================
# PRODUCT SEARCH
# ==========================================================

st.header("🔍 Search a Product")

search_term = st.text_input("Enter a product name or keyword")

if search_term:

    search_results = popularity_df[
        popularity_df["Description"].str.contains(
            search_term,
            case=False,
            na=False,
        )
    ]

    st.success(f"{len(search_results):,} products matched.")

    st.dataframe(
        search_results[
            [
                "StockCode",
                "Description",
                "PopularityScore",
                "PurchaseCount",
                "TotalRevenue",
            ]
        ],
        use_container_width=True,
        hide_index=True,
    )

st.divider()

# ==========================================================
# RECOMMENDATION STRATEGY SUMMARY
# ==========================================================

st.header("🧠 How the Recommendations Work")

strategy_left, strategy_mid, strategy_right = st.columns(3)

with strategy_left:

    st.info(
        """
**Popularity Ranking**

Ranks every product by how often it's purchased and how much
revenue it generates. Works even for new customers with no
purchase history.
"""
    )

with strategy_mid:

    st.info(
        """
**Customer Collaborative Filtering**

Finds customers with similar purchase behaviour to a given
customer, then recommends what those "neighbours" bought.
"""
    )

with strategy_right:

    st.info(
        """
**Item-Item Similarity**

Finds products that are frequently purchased together, so a
customer viewing one product can be shown related ones.
"""
    )

st.divider()

# ==========================================================
# BUSINESS BENEFITS
# ==========================================================

st.header("💼 Business Benefits")

benefit_left, benefit_right = st.columns(2)

with benefit_left:

    st.success(
        """
**Revenue Growth**

- Cross-sell related products
- Upsell higher-value alternatives
- Increase average order value
"""
    )

with benefit_right:

    st.success(
        """
**Customer Experience**

- Faster product discovery
- More relevant browsing
- Higher engagement and repeat visits
"""
    )

st.divider()

# ==========================================================
# INTERACTIVE FILTERS
# ==========================================================

st.header("🎛 Interactive Filters")

filter_col1, filter_col2 = st.columns(2)

with filter_col1:

    min_popularity = st.slider(
        "Minimum Popularity Score",
        float(popularity_df["PopularityScore"].min()),
        float(popularity_df["PopularityScore"].max()),
        float(popularity_df["PopularityScore"].min()),
    )

with filter_col2:

    min_purchase_count = st.slider(
        "Minimum Purchase Count",
        int(popularity_df["PurchaseCount"].min()),
        int(popularity_df["PurchaseCount"].max()),
        int(popularity_df["PurchaseCount"].min()),
    )

filtered_products = popularity_df[
    (popularity_df["PopularityScore"] >= min_popularity)
    & (popularity_df["PurchaseCount"] >= min_purchase_count)
]

st.success(f"{len(filtered_products):,} products match these filters.")

st.dataframe(
    filtered_products[
        [
            "StockCode",
            "Description",
            "PopularityScore",
            "PurchaseCount",
            "TotalRevenue",
        ]
    ].head(200),
    use_container_width=True,
    hide_index=True,
)

download_csv = filtered_products.to_csv(index=False).encode("utf-8")

st.download_button(
    "📥 Download Filtered Product Recommendations",
    data=download_csv,
    file_name="filtered_product_recommendations.csv",
    mime="text/csv",
)

st.divider()

# ==========================================================
# KEY OBSERVATIONS (COMPUTED FROM THIS DATASET)
# ==========================================================

st.header("📌 Key Observations")

st.caption(
    "These insights are computed live from the recommendation data above - nothing here is hardcoded."
)

most_popular_row = popularity_df.sort_values("PopularityRank").iloc[0]

most_similar_pair = item_df.sort_values("SimilarityScore", ascending=False).iloc[0]

avg_recommendations_per_customer = (
    customer_df.groupby("CustomerID").size().mean()
)

obs1, obs2 = st.columns(2)

with obs1:

    st.info(
        f"**Most popular product:** \"{most_popular_row['Description']}\" "
        f"leads with a popularity score of "
        f"{most_popular_row['PopularityScore']:.2f}."
    )

    st.info(
        f"**Strongest product pairing:** \"{most_similar_pair['Description']}\" "
        f"has the highest similarity score in the dataset, at "
        f"{most_similar_pair['SimilarityScore']:.3f}."
    )

with obs2:

    st.info(
        f"**Avg recommendations per customer:** Each customer receives "
        f"about {avg_recommendations_per_customer:.1f} recommended products "
        f"on average."
    )

    st.info(
        f"**Coverage:** {total_customers_covered:,} customers and "
        f"{total_products:,} products are covered across all three "
        f"recommendation engines."
    )

st.divider()

# ==========================================================
# NAVIGATION
# ==========================================================

nav_left, nav_right = st.columns(2)

with nav_left:

    st.caption("⬅ Previous Page: Churn Prediction")

with nav_right:

    st.caption("➡ Next Page: Business Insights")